# Zebra cargo configuration

# TODO: Remove when ZSA is stable
[target.'cfg(all())']
rustflags = [
    "--cfg", 'feature="tx_v6"',
    "--cfg", "zcash_unstable=\"nu7\"",
]

[build]
rustdocflags = [
    # Enable tx_v6 everywhere by default
    "--cfg", 'feature="tx_v6"',

    # TODO: Remove when ZSA is stable
    "--cfg", "zcash_unstable=\"nu7\"",

    # Links in public docs can point to private items.
    "-Arustdoc::private_intra_doc_links",
]

[env]
RUST_BACKTRACE = "1"

[profile.profiling]
inherits = "release"
debug = true
