name: Basic checks

#on: [push, pull_request]
on: [push]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies on Ubuntu
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler build-essential librocksdb-dev
      - name: Run tests
        run: ROCKSDB_LIB_DIR=/usr/lib SNAPPY_LIB_DIR=/usr/lib/x86_64-linux-gnu cargo test --verbose
      - name: Verify working directory is clean
        run: git diff --exit-code
      - name: Run doc check
        run: cargo doc --all-features --document-private-items
      - name: Run format check
        run: cargo fmt -- --check
